---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-hookshot
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: matrix-hookshot
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: registration.yml
      remoteRef:
        key: matrix-hookshot
        property: registration
    - secretKey: passkey.pem
      remoteRef:
        key: matrix-hookshot
        property: passkey
