---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix-hookshot
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: matrix-hookshot
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        registration.yml: "{{ .registration }}"
        passkey.pem: "{{ .passkey }}"
        github-private-key.pem: "{{ .githubPrivateKey }}"
        github.yml: |
          github:
            auth:
              id: 4906005
              privateKeyFile: /run/secrets/matrix-hookshot/github-private-key.pem
            webhook:
              secret: {{ .githubWebhookSecret | quote }}
            defaultOptions:
              showIssueRoomLink: true
  data:
    - secretKey: registration
      remoteRef:
        key: matrix-hookshot
        property: registration
    - secretKey: passkey
      remoteRef:
        key: matrix-hookshot
        property: passkey
    - secretKey: githubPrivateKey
      remoteRef:
        key: matrix-github-app
        property: private-key
    - secretKey: githubWebhookSecret
      remoteRef:
        key: matrix-github-app
        property: webhook-secret
