---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vpn
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vpn",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.90",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {"dst": "0.0.0.0/5", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "8.0.0.0/7", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "11.0.0.0/8", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "12.0.0.0/6", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "16.0.0.0/4", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "32.0.0.0/3", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "64.0.0.0/2", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "128.0.0.0/3", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "160.0.0.0/5", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "168.0.0.0/6", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "172.0.0.0/12", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "172.32.0.0/11", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "172.64.0.0/10", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "172.128.0.0/9", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "173.0.0.0/8", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "174.0.0.0/7", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "176.0.0.0/4", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "192.0.0.0/9", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "192.128.0.0/11", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "192.160.0.0/13", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "192.169.0.0/16", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "192.170.0.0/15", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "192.172.0.0/14", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "192.176.0.0/12", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "192.192.0.0/10", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "193.0.0.0/8", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "194.0.0.0/7", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "196.0.0.0/6", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "200.0.0.0/5", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "208.0.0.0/4", "gw": ${VPN_GATEWAY_IP} },
              {"dst": "224.0.0.0/3", "gw": ${VPN_GATEWAY_IP} }
            ]
          }
        }
      ]
    }
