---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: direwolf-operator
spec:
  interval: 30m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:d097c1549f5350ed3405ddf4c5323fabb5465df11ae6c17c81e3a3df1d9fdbae
  url: oci://ghcr.io/games-on-whales/charts/direwolf-operator
