FROM ghcr.io/siderolabs/nvidia-open-gpu-kernel-modules-production:595.71.05-v1.13.5@sha256:620835af320adae38d5d4788491131023be7430f3000c52f0fb54661eaef4e1d

COPY modules/ /rootfs/usr/lib/modules/6.18.36-talos/kernel/drivers/video/
COPY manifest.yaml /manifest.yaml
