---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-infra
configMapGenerator:
  - name: amd-fan-control-script
    files:
      - fanctl.py
resources:
  - ./daemonset.yaml
  - ./fan-control.yaml
  - ./grafanadashboard.yaml
