---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: ${APP}
spec:
  callbackUrls:
    - "https://${APP_URL}/oidc/callback"
    - "https://${APP_URL}/user-settings"
    - "app.immich://oauth-callback"
