---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: APP-app-vars
    literals:
      - APP=opencloud
      - VOLSYNC_CAPACITY=10Gi
      - VOLSYNC_STORAGECLASS=ceph-filesystem
      - VOLSYNC_SNAPSHOTCLASS=csi-ceph-filesystem
      - VOLSYNC_ACCESSMODES=ReadWriteMany
components:
  - ../../../components/ks/app
  - ../../../components/kustomize/external-secret
  - ../../../components/kustomize/volsync
  # - ../../../components/kustomize/nfs
