---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firecrawl
spec:
  refreshPolicy: OnChange
  target:
    name: firecrawl
    template:
      engineVersion: v2
      data:
        RABBITMQ_DEFAULT_PASS: "{{ .password }}"
        rabbitmq-url: "amqp://firecrawl:{{ .password }}@firecrawl-rabbitmq:5672"
  dataFrom:
    - sourceRef:
        generatorRef:
          kind: ClusterGenerator
          name: cnpg-pass-generator
