---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./model
configMapGenerator:
  - name: APP-app-vars
    literals:
      - APP=laguna
components:
  - ../../../components/ks/app
