---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: APP-app-vars
    literals:
      - APP=laguna
components:
  - ../../../components/ks/app
patches:
  - target:
      kind: Kustomization
      name: laguna
    patch: |
      - op: replace
        path: /spec/path
        value: ./kubernetes/empty
