---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: opencloud-web
spec:
  clientID: opencloud-web
  isPublic: true
  pkceEnabled: true
  callbackUrls:
    - https://cloud.${DOMAIN_NAME}
    - https://cloud.${DOMAIN_NAME}/oidc-callback.html
    - https://cloud.${DOMAIN_NAME}/oidc-silent-redirect.html
  allowedUserGroups:
    - name: opencloud-admins
    - name: opencloud-users
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: opencloud-ios
spec:
  clientID: OpenCloudIOS
  isPublic: true
  pkceEnabled: true
  callbackUrls:
    - oc://ios.opencloud.eu
  logoutCallbackUrls:
    - oc://ios.opencloud.eu
  allowedUserGroups:
    - name: opencloud-admins
    - name: opencloud-users
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDOIDCClient
metadata:
  name: opencloud-desktop
spec:
  clientID: OpenCloudDesktop
  isPublic: true
  pkceEnabled: true
  callbackUrls:
    - http://127.0.0.1
    - http://localhost
  allowedUserGroups:
    - name: opencloud-admins
    - name: opencloud-users
