FROM ghcr.io/allenporter/flux-local:v8.4.0@sha256:c0be852e30f299ce6a220cc992b0c21a2a0b0684cc17713b9d718e18d9c8beff

USER root
RUN apk add --no-cache bash=5.3.9-r1 \
    && mkdir -p /work /home/gate/.cache /home/gate/.config /home/gate/.local/share \
    && chown 1001:1001 /work \
    && chown -R 1001:1001 /home/gate
ENV HOME=/home/gate \
    XDG_CACHE_HOME=/home/gate/.cache \
    XDG_CONFIG_HOME=/home/gate/.config \
    XDG_DATA_HOME=/home/gate/.local/share
USER 1001
