---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  # Default is to include import only, since most apps only need the certs to be present.
  - ./import
