apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-plugin-configs
  namespace: nvidia-device-plugin # Ensure this matches where your plugin runs
data:
  config.yaml: |
    version: v1
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 4
