apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/hr
configMapGenerator:
- files:
  - fanctl.py
  name: fan-control-script
kind: Kustomization
namespace: cluster-infra
resources:
- ./fan-control.yaml
- ./gpu-sharing-config.yaml
- ./helmrelease.yaml
- ./helmrepository.yaml
- ./power-limit.yaml
- ./runtimeclass.yaml
