---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dreamcast
resources:
  - ./gaming-priority.yaml
  - ./wolf-entrypoint.yaml
  - ./user.yaml
  - ./testball.yaml
  - ./steam.yaml
