---
apiVersion: direwolf.games-on-whales.github.io/v1alpha1
kind: User
metadata:
  name: tim
spec:
  resources:
    limits:
      nvidia.com/gpu: "1"
      memory: 24Gi
    requests:
      nvidia.com/gpu: "1"
  volumes:
    - name: wolf-root-entrypoint
      configMap:
        name: wolf-root-entrypoint
        defaultMode: 0755
    - name: udev-data
      emptyDir: {}
  sidecarPolicies:
    wolf:
      env:
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: GBM_BACKENDS_PATH
          value: /usr/local/lib/gbm:/usr/lib/x86_64-linux-gnu/gbm
      volumeMounts:
        - name: wolf-root-entrypoint
          mountPath: /entrypoint.sh
          subPath: entrypoint.sh
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
          nvidia.com/gpu: "1"
          squat.ai/uinput: "1"
        limits:
          memory: 4Gi
          nvidia.com/gpu: "1"
          squat.ai/uinput: "1"
    wolfAgent:
      volumeMounts:
        - name: udev-data
          mountPath: /run/udev
      securityContext:
        capabilities:
          add: [NET_ADMIN]
