---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./ks.yaml
patches:
  - path: ../common/base/ks.yaml
    target: &ks
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
      labelSelector: "components.autoreiv/ks=app-resources"
replacements:
  - path: ../common/base/replacements.yaml
  - source:
      kind: ConfigMap
      name: APP-app-vars
      fieldPath: data.RESOURCES
    targets:
      - select: *ks
        fieldPaths:
          - spec.path
        options:
          delimiter: /
          index: 5
      - select: *ks
        fieldPaths:
          - metadata.name
        options:
          delimiter: '-'
          index: 1
  - source:
      kind: ConfigMap
      name: APP-app-vars
      fieldPath: data.APP
    targets:
      - select: *ks
        fieldPaths:
          - spec.dependsOn.0.name
        options:
          create: true
      - select: *ks
        fieldPaths:
          - metadata.name
          - spec.commonMetadata.labels.app\.kubernetes\.io/name
          - spec.postBuild.substituteFrom.0.name
        options:
          delimiter: '-'
          index: 0
          create: true
