---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ./deps
patches:
  - patch: |-
      - op: add
        path: /spec/components/-
        value: ../../../../components/external-secret
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
  
