---
# yaml-language-server: $schema=https://raw.githubusercontent.com/external-secrets/external-secrets/refs/heads/main/deploy/charts/external-secrets/values.schema.json
installCRDs: true
leaderElect: true
serviceMonitor:
  enabled: true
grafanaDashboard:
  enabled: true
certController:
  image:
    repository: ghcr.io/external-secrets/external-secrets
  serviceMonitor:
    enabled: true
    interval: 1m
webhook:
  image:
    repository: ghcr.io/external-secrets/external-secrets
  serviceMonitor:
    enabled: true
    interval: 1m
  replicaCount: 2
image:
  repository: ghcr.io/external-secrets/external-secrets
  
