---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: ./patch.yaml
    target:
      kind: Namespace
replacements:
  - source:
      kind: Namespace
      fieldPath: metadata.name
    targets:
      - select:
          kind: Namespace
        fieldPaths:
          - metadata.name
      - select: &ks
          kind: Kustomization
          group: kustomize.toolkit.fluxcd.io
        fieldPaths:
          - spec.commonMetadata.labels.app\.kubernetes\.io/namespace
        options:
          create: true
      - select: *ks
        fieldPaths:
          - spec.path
        options:
          index: 3
          delimiter: /
      - select:
          <<: *ks
          labelSelector: kustomize.autoreiv/targetNS!=false
        fieldPaths:
          - spec.targetNamespace
        options:
          create: true
      - select:
          kind: ConfigMap
          labelSelector: kustomize.autoreiv/app-vars
        fieldPaths:
          - data.NS
        options:
          create: true
