---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/tags/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blocky
spec:
  interval: 1h
  maxHistory: 1
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    timeout: 2m
    remediation:
      retries: 1
  upgrade:
    timeout: 2m
    remediation:
      retries: 1
  values:
    controllers:
      blocky:
        strategy: RollingUpdate
        replicas: 3
        rollingUpdate:
          surge: 1
          unavailable: 1
        pod:
          # tolerations:
          #   - key: "rpi"
          #     operator: "Equal"
          #     value: "true"
          #     effect: "NoSchedule"
          # affinity:
          #   podAntiAffinity:
          #     requiredDuringSchedulingIgnoredDuringExecution:
          #       - labelSelector:
          #           matchLabels:
          #             app.kubernetes.io/instance: blocky
          #         topologyKey: kubernetes.io/hostname
          hostUsers: false
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile: { type: RuntimeDefault }
        containers:
          main:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: v0.29.0@sha256:a6d99f323d3036a99a3767a52ad612f4d8f3f31167492bfc14d4ea57b24cdfd0
            env:
              PGCONNECT_TIMEOUT: 10
              PGHOST:
                valueFrom:
                  secretKeyRef:
                    name: blocky-db-app
                    key: host
              PGPORT:
                valueFrom:
                  secretKeyRef:
                    name: blocky-db-app
                    key: port
              PGUSER:
                valueFrom:
                  secretKeyRef:
                    name: blocky-db-app
                    key: username
              PGPASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: blocky-db-app
                    key: password
              PGDATABASE:
                valueFrom:
                  secretKeyRef:
                    name: blocky-db-app
                    key: dbname
            probes:
              readiness: &probes
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /app/blocky
                      - healthcheck
              liveness: *probes
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                add:
                  - NET_BIND_SERVICE
                drop:
                  - ALL
    service:
      dns:
        controller: blocky
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "${BLOCKY_LB_IP:-1.1.1.1}"
          coredns.io/hostname: dot.${DOMAIN_NAME}
        ports: &p
          dns-tcp:
            port: 53
          dns-udp:
            port: 53
            protocol: UDP
          dns-tls:
            port: 853
      k8s:
        controller: blocky
        clusterIP: "${BLOCKY_CLUSTER_IP:-1.1.1.1}"
        ports:
          <<: *p
          http:
            port: &port 4000
    serviceMonitor:
      blocky:
        serviceName: blocky-k8s
        endpoints:
          - port: http
    route:
      blocky-DOH:
        annotations:
          # google.com base64
          gatus.home-operations.com/endpoint: |-
            url: https://dns.${DOMAIN_NAME}/dns-query?dns=AAABAAABAAAAAAAABmdvb2dsZQNjb20AAAEAAQ
        hostnames:
          - dns.${DOMAIN_NAME}
        parentRefs:
          - name: envoy-external
            namespace: envoy-gateway
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /dns-query
            backendRefs:
              - identifier: k8s
                port: *port
    persistence:
      config:
        type: configMap
        name: blocky
        globalMounts:
          - path: /app/config.yml
            subPath: config.yml
      tls:
        type: secret
        name: blocky-tls
        globalMounts:
          - path: /certs/tls.crt
            subPath: tls.crt
          - path: /certs/tls.key
            subPath: tls.key
    configMaps:
      config:
        data:
          config.yml: |
            caching:
              minTime: 2m
              maxTime: 1h
              maxItemsCount: 0
              prefetching: true
              prefetchExpires: 1h
              prefetchThreshold: 30
              prefetchMaxItemsCount: 0
              cacheTimeNegative: -1
              exclude:
                - '/(^|\\.)${DOMAIN_NAME//./\\.}$/'
                - '/\\.internal$/'
                - '/(^|\\.)cluster\\.local$/'
                - '/(^|\\.)in-addr\\.arpa$/'
            
            log:
              level: info
            
            connectIPVersion: v4
            minTlsServeVersion: 1.3
            certFile: /certs/tls.crt
            keyFile: /certs/tls.key
            ports:
              dns: 53
              tls: 853
              http: 4000
            
            prometheus:
              enable: true
            
            conditional:
              fallbackUpstream: false
              mapping:
                ${DOMAIN_NAME}: ${UNIFI_DNS_IP}:53

                # House
                internal: ${UNIFI_DNS_IP}:53
                168.192.in-addr.arpa: ${UNIFI_DNS_IP}:53
                # kube
                cluster.local: ${COREDNS_CLUSTER_IP}
                16.172.in-addr.arpa: ${COREDNS_CLUSTER_IP}
            
            # ClientLookup is set to blocky so it can conditionally forward it to coredns/apt/house DHCP
            clientLookup:
              upstream: 127.0.0.1
              clients:
                localhost:
                  - 127.0.0.1
            
            # To resolve devices behind coredns
            ecs:
              useAsClient: true
              forward: false
            
            bootstrapDns:
              - 8.8.8.8
              - 1.1.1.1
              - 9.9.9.9
            
            upstreams:
              groups:
                default:
                  - https://dns.quad9.net/dns-query
                  - https://freedns.controld.com/p0
                  - https://doh.opendns.com/dns-query
                  - https://cloudflare-dns.com/dns-query
            
            blocking:
              denylists:
                ads:
                  - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/multi.txt
              allowlists:
                ads:
                  - |
                    epi-graphql.conde.digital
              clientGroupsBlock:
                ${VPN_CIDR}:
                  - ads

            filtering:
              queryTypes:
                - AAAA

            redis:
              address: blocky-dragonfly-db:6379
              connectionAttempts: 10
              connectionCooldown: 60s
            
            queryLog:
              type: postgresql
              logRetentionDays: 90
              creationAttempts: 5
              creationCooldown: 60s
              flushInterval: 5s
    