---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: APP-app-vars
    literals:
      - APP=hermes
      - SUBDOMAIN=hermes
      - VOLSYNC_CAPACITY=2Gi
components:
  - ../../../components/ks/app/subdomain
  - ../../../components/kustomize/external-secret
  - ../../../components/kustomize/pocket-id/deps
  - ../../../components/kustomize/volsync
