apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/hr
kind: Kustomization
namespace: network
resources:
- ./dnsendpoint.yaml
- ./externalsecret.yaml
- ./grafanadashboard.yaml
- ./helmrelease.yaml
