---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: APP-app-vars
    literals:
      - APP=rook-ceph-cluster
      - DRIFT_DETECTION=disabled
patches:
  - patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: rook-ceph
    target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
components:
  - ../../../components/ks/app
  - ../../../components/kustomize/external-secret
