---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: open-webui-users
spec:
  users:
    usernames:
      - tim
  customClaims:
    - key: groups
      value: user
---
apiVersion: pocketid.internal/v1alpha1
kind: PocketIDUserGroup
metadata:
  name: open-webui-admins
spec:
  users:
    usernames:
      - tim
  customClaims:
    - key: groups
      value: admin
