---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: llm-operator
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - llm-operator
      - key: app.kubernetes.io/name
        operator: In
        values:
          - llm-operator
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_service_name
          regex: llm-operator-metrics
          action: keep
        - replacement: llm-operator
          targetLabel: controller
