---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: matrix-coordinator-bot-plugin
    options:
      disableNameSuffixHash: true
    files:
      - maubot.yaml=./maubot.yaml
      - base-config.yaml=./base-config.yaml
      - cogito_bot.py=./cogito_bot.py
  - name: matrix-coordinator-dashboard
    options:
      disableNameSuffixHash: true
    files:
      - matrix-coordinator.json=./dashboard/matrix-coordinator.json
resources:
  - ./bot-secret.yaml
  - ./externalsecret.yaml
  - ./github-app.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./servicemonitor.yaml
  - ./grafanadashboard.yaml
  - ./prometheusrule.yaml
