---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-huggingface-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: openebs-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-vllm-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: openebs-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-triton-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: openebs-hostpath
