---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./gemma-4/31b-qat-awq-int4.yaml
  - ./gemma-4/31b-it-qat-w4a16-ct.yaml
  - ./gemma-4/gemma4-agentic.yaml
  - ./qwen-3-6/27b-autoround.yaml
  - ./qwen-3-6/27b-fable-fusion-heretic.yaml
  - ./qwen-3-6/fable-fusion-heretic-thinking.yaml
  - ./qwen-3-6/fable-fusion-heretic-coding.yaml
  - ./qwen-3-6/fable-fusion-heretic-instruct.yaml
