---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ntfy-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ntfy-credentials
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        tim_password: "{{ .tim_password }}"
        agent_password: "{{ .agent_password }}"
        auth_users: '{{ printf "%s:user,%s:user" (htpasswd "tim" .tim_password) (htpasswd "agent" .agent_password) }}'
  data:
    - secretKey: tim_password
      remoteRef:
        key: ntfy
        property: NTFY_TIM_PASSWORD
    - secretKey: agent_password
      remoteRef:
        key: ntfy
        property: NTFY_AGENT_PASSWORD
