---
# yaml-language-server: $schema=https://crd.movishell.pl/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${APP}-db
spec:
  affinity:
    podAntiAffinityType: ${CNPG_AFFINITY_TYPE:=required}
  instances: ${CNPG_REPLICAS:=3}
  primaryUpdateStrategy: ${CNPG_UPDATE_STRAT:=unsupervised}
  primaryUpdateMethod: switchover
  enablePDB: true
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    major: ${CNPG_MAJOR_VERSION:-18}
    name: ${CNPG_CATALOG_NAME:-postgresql-minimal-trixie}
  storage:
    size: ${CNPG_CAPACITY:=2Gi}
    storageClass: ${CNPG_STORAGECLASS:=openebs-hostpath}
  superuserSecret:
    name: cloudnative-pg
  enableSuperuserAccess: true
  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: preferred
      # TODO(blakely): Reenable when the old cnpg is gone.
      # failoverQuorum: true
    parameters:
      shared_buffers: "${CNPG_BUFFERS:=512MB}"
      work_mem: "${CNPG_WORK_MEM:=8MB}"
      maintenance_work_mem: "${CNPG_MAINTENANCE_WORK_MEM:=128MB}"
      effective_cache_size: "${CNPG_CACHE_SIZE:=1536MB}"

      wal_buffers: "${CNPG_WAL_BUFFERS:=16MB}"
      checkpoint_timeout: "${CNPG_CHECKPOINT_TIMEOUT:=10min}"
      max_wal_size: "${CNPG_MAX_WAL_SIZE:=4GB}"
      min_wal_size: "${CNPG_MIN_WAL_SIZE:=1GB}"
      max_slot_wal_keep_size: "${CNPG_MAX_SLOT_WAL_KEEP_SIZE:=10GB}"
      checkpoint_completion_target: "${CNPG_CHECKPOINT_COMPLETION_TARGET:='0.9'}"
      wal_keep_size: "${CNPG_WAL_KEEP_SIZE:=4GB}"
      wal_sender_timeout: 60s
      wal_receiver_timeout: 60s

      log_min_duration_statement: "500"
      log_checkpoints: "on"
      log_autovacuum_min_duration: "250"
      log_temp_files: "128MB"
      log_lock_waits: "on"

      autovacuum_vacuum_cost_limit: "${CNPG_AUTOVACUUM_COST_LIMIT:='2000'}"
      autovacuum_max_workers: "${CNPG_AUTOVACUUM_MAX_WORKERS:='3'}"
      autovacuum_naptime: "${CNPG_AUTOVACUUM_NAPTIME:=20s}"
