---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ${APP}-db-${CNPG_USER:=app}
  labels:
    autoreiv.io/component: cnpg
spec:
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: ${NS}
  externalSecretSpec:
    refreshPolicy: OnChange
    target:
      creationPolicy: Orphan
      template:
        engineVersion: v2
        metadata:
          labels:
            cnpg.io/cluster: ${APP}-db
            cnpg.io/userType: app
            cnpg.io/reload: "true" # reloads cluster w/ password if changed
        data:
          user: ${CNPG_USER:=app}
          username: ${CNPG_USER:=app}
          dbname: ${CNPG_DB:=app}
          host: "${APP}-pooler-rw.${NS}.svc.cluster.local"
          password: "{{ .password }}"
          port: "5432"
          pgpass: "${APP}-pooler-rw.${NS}.svc.cluster.local:5432:${CNPG_DB:=app}:${CNPG_USER:=app}:{{ .password }}"
          jdbc-uri: "jdbc:postgresql://${APP}-pooler-rw.${NS}.svc.cluster.local:5432/${CNPG_DB:=app}?password={{ .password }}&user=${CNPG_USER:=app}"
          uri: "postgresql://${CNPG_USER:=app}:{{ .password }}@${APP}-pooler-rw.${NS}.svc.cluster.local:5432/${CNPG_DB:=app}"
    dataFrom:
      - sourceRef:
          generatorRef:
            kind: ClusterGenerator
            name: cnpg-pass-generator
# ---
# apiVersion: external-secrets.io/v1alpha1
# kind: PushSecret
# metadata:
#   name: &sName ${APP}-db-${CNPG_USER:=app}
# spec:
#   updatePolicy: Replace
#   deletionPolicy: Delete
#   refreshInterval: 1h
#   secretStoreRefs:
#     - name: onepassword-connect
#       kind: ClusterSecretStore
#   selector:
#     secret:
#       name: *sName
#   data:
#     - match:
#         remoteRef:
#           remoteKey: *sName
