---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/cluster: ${APP}-db
  name: ${APP}-db
spec:
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      cnpg.io/cluster: ${APP}-db
      cnpg.io/podRole: instance
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    cnpg.io/poolerName: ${APP}-pooler-rw
  name: ${APP}-pooler-rw
spec:
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      cnpg.io/podRole: pooler
      cnpg.io/poolerName: ${APP}-pooler-rw
      
