apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: flashnext
spec:
  modelName: flashnext
  proxyRef: litellm
  params:
    model: openai/qwen3.8-flash-next
    apiBase: http://flashnext.llm.svc.cluster.local:8080/v1
    apiKey: not-needed
    additional:
      timeout: 1800
  info:
    supportsFunctionCalling: true
    maxInputTokens: 131072
    maxOutputTokens: 8192
    extra:
      input_cost_per_token: 0
      output_cost_per_token: 0
      supports_reasoning: true
