---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: muse-glimmer-30b
spec:
  modelName: Muse-Glimmer-30B
  proxyRef: litellm
  params:
    model: openai/muse-glimmer-30b
    apiBase: http://muse-glimmer-30b.llm.svc.cluster.local:8080/v1
    apiKey: not-needed
    additional:
      timeout: 600
  info:
    supportsFunctionCalling: true
    supportsVision: true
    maxInputTokens: 131072
    maxOutputTokens: 16384
    extra:
      input_cost_per_token: 0
      output_cost_per_token: 0
      supports_reasoning: true
