---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./helmrelease.yaml
  - ./servicemonitor.yaml
configMapGenerator:
  - name: gemma4-canonical-chat-template
    files:
      - gemma4-canonical-chat-template.jinja
    options:
      disableNameSuffixHash: true
