#!/usr/bin/env python3
"""Generate hermes-agent-bundle ConfigMap from the adjacent agent-bundle/ tree.

The bundle (custom skills, model-provider plugins, personality/memory seeds)
ships to the cluster Hermes pod as one tarball in ConfigMap binaryData:
ConfigMap keys cannot contain '/', so per-file keys would mangle the tree.

Usage: .venv/bin/python gen-bundle.py [--check]
       (--check exits 1 if the committed bundle.yaml is stale)
"""

import argparse
import base64
import gzip
import hashlib
import io
import re
import sys
import tarfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "agent-bundle"
OUT = HERE / "bundle.yaml"
HR = HERE / "helmrelease.yaml"
CONFIGURE = HERE / "configure.py"
BOOTSTRAP = HERE / "provider-bootstrap.yaml"
ANNOT = "hermes.home-operations.com/bundle-sha256"
HEADER = """---
# GENERATED by gen-bundle.py from agent-bundle/ — do not edit by hand.
# The Hermes configure-provider init container unpacks this tarball into
# /opt/data (skills/, plugins/model-providers/, SOUL.md, memories/) before
# every start. Regenerate after changing agent-bundle/:
#   ../.venv/bin/python gen-bundle.py   # from kubernetes/apps/llm/hermes/app
apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes-agent-bundle
binaryData:
  bundle.tgz: |-
"""


def build_tarball() -> bytes:
    buf = io.BytesIO()
    # Deterministic: sorted entries, zeroed uid/gid/uname, fixed mtime,
    # gzip header mtime pinned to 0 (plain `w:gz` embeds wall-clock time).
    files = sorted(
        p for p in SRC.rglob("*")
        if p.is_file() and "__pycache__" not in p.parts
    )
    with gzip.GzipFile(fileobj=buf, mode="wb", mtime=0) as gz:
        with tarfile.open(fileobj=gz, mode="w") as tf:
            for p in files:
                info = tf.gettarinfo(str(p), arcname=str(p.relative_to(SRC)))
                info.uid = info.gid = 0
                info.uname = info.gname = ""
                info.mtime = 0
                with p.open("rb") as fh:
                    tf.addfile(info, fh)
    return buf.getvalue()


def render(blob: bytes) -> str:
    # Single-line base64: binaryData decoding rejects embedded newlines, and
    # a folded scalar would inject spaces at the wrap points.
    b64 = base64.b64encode(blob).decode()
    return HEADER + "    " + b64 + "\n"


def render_configure_configmap() -> str:
    """Embed configure.py verbatim into the hermes-provider-bootstrap ConfigMap."""
    cfg = CONFIGURE.read_text()
    return '''---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hermes-provider-bootstrap
data:
  configure.py: |
''' + "\n".join("    " + line for line in cfg.splitlines()) + "\n"


def stamp_pod_annotation(blob: bytes) -> None:
    """Write the bundle digest into the pod-template annotation so a bundle
    change alters the pod hash and Flux/app-template rolls the deployment."""
    digest = hashlib.sha256(blob).hexdigest()
    text = HR.read_text()
    old_line = next((l for l in text.splitlines() if ANNOT in l), None)
    if old_line is None:
        raise SystemExit(f"helmrelease.yaml missing {ANNOT} annotation")
    new_line = re.sub(
        rf'({re.escape(ANNOT)}: )"[^"]*"', rf'\1"{digest}"', old_line
    )
    if new_line != old_line:
        HR.write_text(text.replace(old_line, new_line))
        print(f"stamped {ANNOT}={digest[:12]} in helmrelease.yaml")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not SRC.is_dir():
        print(f"missing {SRC}", file=sys.stderr)
        return 1
    blob = build_tarball()
    rendered = render(blob)
    bootstrap = render_configure_configmap()
    digest = hashlib.sha256(blob).hexdigest()
    annotated = bool(re.search(rf'{re.escape(ANNOT)}: "{digest}"', HR.read_text()))
    if args.check:
        fresh = (
            OUT.exists() and OUT.read_text() == rendered
            and BOOTSTRAP.exists() and BOOTSTRAP.read_text() == bootstrap
            and annotated
        )
        if fresh:
            print("bundle.yaml, provider-bootstrap.yaml, and pod annotation are current")
            return 0
        print("generated artifact is stale — run gen-bundle.py", file=sys.stderr)
        return 1
    OUT.write_text(rendered)
    BOOTSTRAP.write_text(bootstrap)
    stamp_pod_annotation(blob)
    print(f"wrote {OUT} ({len(rendered)} bytes) and {BOOTSTRAP}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
