---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: hermes-matrix-password
spec:
  length: 48
  digits: 8
  symbols: 8
  symbolCharacters: "-_.~"
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-matrix
spec:
  refreshPolicy: CreatedOnce
  target:
    name: hermes-matrix
    creationPolicy: Orphan
    deletionPolicy: Retain
    immutable: true
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        MATRIX_PASSWORD: '{{ .password }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: hermes-matrix-password
