---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-matrix
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hermes-matrix
    creationPolicy: Orphan
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        MATRIX_PASSWORD: '{{ .password }}'
  data:
    - secretKey: password
      remoteRef:
        key: hermes
        property: MATRIX_PASSWORD
