---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: matrix-config
    options:
      disableNameSuffixHash: true
    files:
      - homeserver.yaml=./homeserver.yaml
  - name: matrix-bootstrap
    options:
      disableNameSuffixHash: true
    files:
      - bootstrap.py=./bootstrap.py
resources:
  - gitops-credentials.yaml
  - hookshot-registration.yaml
  - helmrelease.yaml
  - oidc-client.yaml
  - servicemonitor.yaml
  - terraform.yaml
  - usergroup.yaml
