---
apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-room-ids
data:
  implementation_room_id: "!i1huZbgWwv2HH6t70PbUdrGUkKa4Rnh8evm1Fzw5PuY"
  cogito_project_room_id: "!Z5AkE1biq0CAYjxBPct92Fc2LgBxUVcuZFZY9-Nm3O4"
