apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ziV9Nt5vFC3OKLSP/lc=,iv:a7TmBOPBVhr/6nRhj/thCqT350y0JbXCLhSoIoPaHiM=,tag:ovoaVM3jxWBUhteyrgwBpA==,type:str]
sops:
  age:
    - recipient: age1gkk8p097lufrg05ypavh0pveqhsnjh8jng7dtu3p607yn60f2gysntp8t0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc0UrOUZjVC9Xb1ZJNTlS
        UGt4UlJ5aDlHckxySnNrZnZvNnhRaDg0MUVVCjlwNE9DckxuR1hCNlY1UUdFY1VL
        cjlPVE9mVFAxTmFKODdMQnB0OStIbEUKLS0tIHBYVXh3Q0lrakZuMDRRUmthQi9H
        TDhHci9OWkN5VHdRSjNuS0Jvb3gvcTAKF9evwsSgxaDG8CmdsOlbMPI5VQHrA55U
        iYQIAiehRfeVwDfKa6CMZjJOTFO3qbZt6eLz9kQfk3vyW8HCSbQMUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-17T04:53:42Z"
  mac: ENC[AES256_GCM,data:KmKsEn+J4lmatS4i1pNQr48Z+Xa+XWJey8e467PYttLNsvhYKCQVjv689nxw2Gi2+/dA/RTBoOmyFJjkPiQpa8vvD9rfVjiLE7+05hBXVvOpAnh84U2WuplhpYn7oCauuk/7Z/nZa/2YxfNnXeSqH3THjV7m8gV3nZowxED9BWs=,iv:/NhCDI8HM4wZnts39N0AVyq5xnbxnVVugjDdh6GBiLo=,tag:k7tNcppY01WQ7c8R8pP1CA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
