apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:vv+BVt2K9wLiLabb3B5GF039pM4IN5UB4JptK0WUqyM7tm4ucMAhIx/+gn6MNcczgCPBI1mxpb3+MyWdr5S+fLgfk9b72Q51w20=,iv:vk6XeBg9O9fhn/I/VuMuwTWU0pomj8wq2U4DFaiCtkE=,tag:DXp5ptUtDDQKzD01WdZP4w==,type:str]
sops:
  age:
    - recipient: age1gkk8p097lufrg05ypavh0pveqhsnjh8jng7dtu3p607yn60f2gysntp8t0
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueHE1akNMSnRFVHhDaURI
        QkU3RnV0dVdvQWVDb2NJMWJwTXNLUWxsTUUwCjdKUlJBTU5XVzdCcTVicmdKTTZz
        ZU1JRHhuRk55M3RPU2Z3bnE0V0xhMmcKLS0tIEI0dldvOXp2d2hxK0F5SUk1UU8x
        cWJDZmxOWmc3aDg5SzJxR2dESEFUeGcKSpZ7xkL+7B7a1YKcv7O3I8lIhwIhvYv4
        ubpgQIIY4m6Px3dnUtQO1vP5ry7WkkDbKeGlnPGr2O1lPHCG6ESH0w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-17T04:53:41Z"
  mac: ENC[AES256_GCM,data:7PymS9ggjwm6kPgVLAilx9kqx4vMr5IlgMh2cONwe9AcrHDtz50RMR5mCQNIGENb+xcNpvwZHuYSvgD3+lZKE+fR/eVFeTlHw14Z/d4izYKKiRm5rlM5JYK0NT+/6YH61DrqXM4TTPedTVuSyf9vP+ahnqKLIujtIMubgQLZ6M8=,iv:3maW7YYfBpci5aye2ylpWMhuhoneV0Q4hkVCudQsLyQ=,tag:X6hve5TgpbDUcaqswrV8yQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
