---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-artifacts
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: argo-artifacts
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: accessKey
      remoteRef:
        key: argo-workflows
        property: username
    - secretKey: secretKey
      remoteRef:
        key: argo-workflows
        property: credential
