---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: argo-workflows-dashboard
    files:
      - argo-workflows.json=./dashboard/argo-workflows.json
resources:
  - ./externalsecret.yaml
  - ./grafanadashboard.yaml
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./networkpolicy.yaml
  - ./oidc.yaml
  - ./prometheusrule.yaml
generatorOptions:
  disableNameSuffixHash: true
