---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./source.yaml
  - ./crds.yaml
configMapGenerator:
  - name: APP-app-vars
    literals:
      - APP=fenrir
components:
  - ../../../components/ks/app
patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: APP
      spec:
        dependsOn:
          - name: fenrir-crds
    target:
      kind: Kustomization
      group: kustomize.toolkit.fluxcd.io
      labelSelector: components.autoreiv/ks=app
