---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fenrir-source
  namespace: dreamcast
spec:
  interval: 30m
  url: https://github.com/shrinedogg/fenrir.git
  ref:
    branch: feat/multi-user
    commit: 29eb075afe1ab61490196a7272fd21b5b6313cfc
