---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./direwolf.games-on-whales.github.io_apps.yaml
  - ./direwolf.games-on-whales.github.io_pairings.yaml
  - ./direwolf.games-on-whales.github.io_sessions.yaml
  - ./direwolf.games-on-whales.github.io_users.yaml
