---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build vLLM Proxy

on:
  pull_request:
    paths: ["vllm-proxy/**", ".github/workflows/vllm-proxy.yaml"]
  push:
    branches: ["main"]
    paths: ["vllm-proxy/**", ".github/workflows/vllm-proxy.yaml"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: "1.26.0"
      - run: go test ./...
        working-directory: vllm-proxy
      - uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: vllm-proxy
          push: ${{ github.event_name == 'push' }}
          tags: |-
            ghcr.io/timblakely/vllm-proxy:latest
            ghcr.io/timblakely/vllm-proxy:${{ github.sha }}
