---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test vLLM Proxy

on:
  pull_request:
    paths: ["vllm/vllm-proxy/**", ".github/workflows/vllm-proxy.yaml"]
  push:
    branches: ["main"]
    paths: ["vllm/vllm-proxy/**", ".github/workflows/vllm-proxy.yaml"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: "1.26.0"
      - run: go test ./...
        working-directory: vllm/vllm-proxy
