---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: knowledge
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: knowledge
  dataFrom:
    - extract:
        key: knowledge
